services:
  app:
    image: node:20
    container_name: 'express-crean-architecture-play-ground'
    env_file:
      - ./.env
    ports:
      - 3000:3000
    command: sh -c "npm ci && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - db
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: my_database
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: my_database
    ports:
      - 5432:5432
